#!/usr/bin/env bash

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${TAG:-}" ]; then
  echo "Missing TAG!" >&2
  exit 1
fi

SUBS="_TAG=${TAG}"

gcloud builds submit "${SCRIPT_DIR}" \
  --project "${PROJECT_ID}" \
  --config "${SCRIPT_DIR}/cloudbuild.yaml" \
  --substitutions "${SUBS}"
